DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS ORD;
DROP TABLE IF EXISTS BASKET;

CREATE TABLE BASKET (
  ID INTEGER ,

  PRIMARY KEY (ID)
);

CREATE TABLE CLIENT (
  ID INTEGER ,
  BASKET_ID INTEGER ,
  LOG   CHAR(50),
  PASSWORD  INTEGER,

  PRIMARY KEY (ID),
  FOREIGN KEY (BASKET_ID) REFERENCES BASKET (ID)
);

CREATE TABLE ORD (
  ID INTEGER ,
  CLIENT_ID INTEGER,
  ADRESS CHAR(50),
  COMPLETED  bit DEFAULT '0',
  PRIMARY KEY (ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);

CREATE TABLE ITEM (
  ID INTEGER ,
  BASKET_ID INTEGER ,
  ORD_ID INTEGER ,
  NAME   CHAR(50),
  PRICE         INTEGER,

  PRIMARY KEY (ID),
  FOREIGN KEY (ORD_ID) REFERENCES ORD (ID),
  FOREIGN KEY (BASKET_ID) REFERENCES BASKET (ID)
);